/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-10-12 10:25:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Home</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/Home.css\" type=\"text/css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/menustyle.css\" type=\"text/css\"/>\r\n");
      out.write("    <script src=\"Home.js\" ></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        let nextBtn = document.querySelector('.next')\r\n");
      out.write("        let prevBtn = document.querySelector('.prev')\r\n");
      out.write("\r\n");
      out.write("        let slider = document.querySelector('.slider')\r\n");
      out.write("        let sliderList = slider.querySelector('.slider .list')\r\n");
      out.write("        let thumbnail = document.querySelector('.slider .thumbnail')\r\n");
      out.write("        let thumbnailItems = thumbnail.querySelectorAll('.item')\r\n");
      out.write("\r\n");
      out.write("        thumbnail.appendChild(thumbnailItems[0])\r\n");
      out.write("\r\n");
      out.write("        // Function for next button\r\n");
      out.write("        nextBtn.onclick = function() {\r\n");
      out.write("            moveSlider('next')\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        // Function for prev button\r\n");
      out.write("        prevBtn.onclick = function() {\r\n");
      out.write("            moveSlider('prev')\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        function moveSlider(direction) {\r\n");
      out.write("            let sliderItems = sliderList.querySelectorAll('.item')\r\n");
      out.write("            let thumbnailItems = document.querySelectorAll('.thumbnail .item')\r\n");
      out.write("\r\n");
      out.write("            if(direction === 'next'){\r\n");
      out.write("                sliderList.appendChild(sliderItems[0])\r\n");
      out.write("                thumbnail.appendChild(thumbnailItems[0])\r\n");
      out.write("                slider.classList.add('next')\r\n");
      out.write("            } else {\r\n");
      out.write("                sliderList.prepend(sliderItems[sliderItems.length - 1])\r\n");
      out.write("                thumbnail.prepend(thumbnailItems[thumbnailItems.length - 1])\r\n");
      out.write("                slider.classList.add('prev')\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            slider.addEventListener('animationend', function() {\r\n");
      out.write("                if(direction === 'next'){\r\n");
      out.write("                    slider.classList.remove('next')\r\n");
      out.write("                } else {\r\n");
      out.write("                    slider.classList.remove('prev')\r\n");
      out.write("                }\r\n");
      out.write("            }, {once: true}) // Remove the event listener after it's triggered once\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');\r\n");
      out.write("\r\n");
      out.write("        .navdiv{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("            top: 10%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            background-color:rgb(241, 254, 241) ;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            margin-bottom: 0.3%;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo{\r\n");
      out.write("            top: 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo img{\r\n");
      out.write("\r\n");
      out.write("            width : 115px;\r\n");
      out.write("            height : 100px;\r\n");
      out.write("            margin-top: -10px;\r\n");
      out.write("            margin-left: 15%;\r\n");
      out.write("            margin: 10%;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .navbar li{\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            float:left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar a{\r\n");
      out.write("            font-size: medium;\r\n");
      out.write("            font-weight: 650;\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar li:hover{\r\n");
      out.write("            background-color: #548363;\r\n");
      out.write("            color:white;\r\n");
      out.write("            transition:0.6s;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .buttons {\r\n");
      out.write("            background-color: #548363;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            padding: 1px;\r\n");
      out.write("            width: 120px;\r\n");
      out.write("            transition: box-shadow 0.25s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .buttons a{\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-family:'Cinzel';\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .buttons:hover{\r\n");
      out.write("            box-shadow : 0 0 8px rgb(132, 158, 136);\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("            width: 120px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /*Footer styling*/\r\n");
      out.write("        .footer {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            margin-top: 0.3%;\r\n");
      out.write("            bottom: -50%;\r\n");
      out.write("            left: 0px;\r\n");
      out.write("            position:sticky;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background-color:rgb(164, 189, 164) ;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .table {\r\n");
      out.write("            border: 0;\r\n");
      out.write("            padding: 50px;\r\n");
      out.write("            margin-left: 24%;\r\n");
      out.write("            margin-top: 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table td{\r\n");
      out.write("            width: 59px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table img{\r\n");
      out.write("\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            background-color: #000;\r\n");
      out.write("            color: #cb0000;\r\n");
      out.write("            font-family: Poppins;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header{\r\n");
      out.write("            width: 1140px;\r\n");
      out.write("            max-width: 80%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header a{\r\n");
      out.write("            color: #000000;\r\n");
      out.write("            margin-right: 5px;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            transition: 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a.active{\r\n");
      out.write("            background: #000000cb;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header a:hover{\r\n");
      out.write("            background: #14ff72cb;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* slider section  */\r\n");
      out.write("\r\n");
      out.write("        .slider{\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            margin-top: -17px;\r\n");
      out.write("            width: 100vw;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            inset: 0 0 0 0;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item img{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item .content{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 20%;\r\n");
      out.write("            width: 1140px;\r\n");
      out.write("            max-width: 80%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            padding-right: 30%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            color: #000000;\r\n");
      out.write("            text-shadow: 0 5px 10px rgba(250, 250, 250, 0.267);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .slider .list .item .content .title,\r\n");
      out.write("        .slider .list .item .content .type{\r\n");
      out.write("            font-size: 5em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            line-height: 1.3em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .slider .list .item .type{\r\n");
      out.write("            color: #000000cb;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item .button{\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(2, 130px);\r\n");
      out.write("            grid-template-rows: 40px;\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item .button button{\r\n");
      out.write("            border: none;\r\n");
      out.write("            background-color: #fefbfb;\r\n");
      out.write("            font-family: Poppins;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: 0.4s;\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .slider .list .item .button button:hover{\r\n");
      out.write("            letter-spacing: 3px;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item .button button:nth-child(2){\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            border: 1px solid #fff;\r\n");
      out.write("            color: #eee;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* Thumbnail Section  */\r\n");
      out.write("        .thumbnail{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 50px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            width: max-content;\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .thumbnail .item{\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 220px;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .thumbnail .item img{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 5px 0 15px rgba(171, 60, 60, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* nextPrevArrows Section  */\r\n");
      out.write("        .nextPrevArrows{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 80%;\r\n");
      out.write("            right: 52%;\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            max-width: 30%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .nextPrevArrows button{\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background-color: #000000cb;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-family: monospace;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: .5s;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .nextPrevArrows button:hover{\r\n");
      out.write("            background-color: #564c4c;\r\n");
      out.write("            color: #000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animation Part */\r\n");
      out.write("        .slider .list .item:nth-child(1){\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* animation text in first item */\r\n");
      out.write("        .slider .list .item:nth-child(1) .content .title,\r\n");
      out.write("        .slider .list .item:nth-child(1) .content .type,\r\n");
      out.write("        .slider .list .item:nth-child(1) .content .description,\r\n");
      out.write("        .slider .list .item:nth-child(1) .content .buttons\r\n");
      out.write("        {\r\n");
      out.write("            transform: translateY(50px);\r\n");
      out.write("            filter: blur(20px);\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            animation: showContent .5s 1s linear 1 forwards;\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes showContent{\r\n");
      out.write("            to{\r\n");
      out.write("                transform: translateY(0px);\r\n");
      out.write("                filter: blur(0px);\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item:nth-child(1) .content .title{\r\n");
      out.write("            animation-delay: 0.4s !important;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item:nth-child(1) .content .type{\r\n");
      out.write("            animation-delay: 0.6s !important;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item:nth-child(1) .content .description{\r\n");
      out.write("            animation-delay: 0.8s !important;\r\n");
      out.write("        }\r\n");
      out.write("        .slider .list .item:nth-child(1) .content .buttons{\r\n");
      out.write("            animation-delay: 1s !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* Animation for next button click */\r\n");
      out.write("        .slider.next .list .item:nth-child(1) img{\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 220px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 50px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            animation: showImage .5s linear 1 forwards;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes showImage{\r\n");
      out.write("            to{\r\n");
      out.write("                bottom: 0;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                border-radius: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .slider.next .thumbnail .item:nth-last-child(1){\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            animation: showThumbnail .5s linear 1 forwards;\r\n");
      out.write("        }\r\n");
      out.write("        .slider.prev .list .item img{\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        @keyframes showThumbnail{\r\n");
      out.write("            from{\r\n");
      out.write("                width: 0;\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .slider.next .thumbnail{\r\n");
      out.write("            animation: effectNext .5s linear 1 forwards;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes effectNext{\r\n");
      out.write("            from{\r\n");
      out.write("                transform: translateX(150px);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* Animation for prev button click */\r\n");
      out.write("        .slider.prev .list .item:nth-child(2){\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .slider.prev .list .item:nth-child(2) img{\r\n");
      out.write("            animation: outFrame 0.5s linear 1 forwards;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes outFrame{\r\n");
      out.write("            to{\r\n");
      out.write("                width: 150px;\r\n");
      out.write("                height: 220px;\r\n");
      out.write("                bottom: 50px;\r\n");
      out.write("                left: 50%;\r\n");
      out.write("                border-radius: 20px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .slider.prev .thumbnail .item:nth-child(1){\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            animation: showThumbnail .5s linear 1 forwards;\r\n");
      out.write("        }\r\n");
      out.write("        .slider.next .nextPrevArrows button,\r\n");
      out.write("        .slider.prev .nextPrevArrows button{\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .slider.prev .list .item:nth-child(2) .content .title,\r\n");
      out.write("        .slider.prev .list .item:nth-child(2) .content .type,\r\n");
      out.write("        .slider.prev .list .item:nth-child(2) .content .description,\r\n");
      out.write("        .slider.prev .list .item:nth-child(2) .content .buttons\r\n");
      out.write("        {\r\n");
      out.write("            animation: contentOut 1.5s linear 1 forwards!important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes contentOut{\r\n");
      out.write("            to{\r\n");
      out.write("                transform: translateY(-150px);\r\n");
      out.write("                filter: blur(20px);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        @media screen and (max-width: 678px) {\r\n");
      out.write("            .slider .list .item .content{\r\n");
      out.write("                padding-right: 0;\r\n");
      out.write("            }\r\n");
      out.write("            .slider .list .item .content .title{\r\n");
      out.write("                font-size: 50px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class = \"navdiv\">\r\n");
      out.write("    <div class = \"logo\"> <a href = \"Home.jsp\"><img src = \"./images/SLIIT%20IMS.png\"></a></div>\r\n");
      out.write("    <nav class = \"navbar\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href = \"Home.jsp\">Home</a></li>\r\n");
      out.write("            <li><a href = \"\">Club & Society</a></li>\r\n");
      out.write("            <li><a href = \"\">Event & News</a></li>\r\n");
      out.write("            <li><a href = \"\">Sports</a></li>\r\n");
      out.write("            <li><a href = \"\">Contact Us</a></li>\r\n");
      out.write("            <li><a href = \"\">About Us</a></li>\r\n");
      out.write("            <button class=\"buttons\"><a href = \"\">Register</a></button>\r\n");
      out.write("            <button class=\"buttons\"><a href = \"\">Login</a></button>\r\n");
      out.write("            <button class=\"buttons\"><a href = \"\">Profile</a></button>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"slider\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"list\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"./images/pexels-photo-2132891.jpeg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"title\" style=\"font-size: 100px; margin-top: -50px \">Welcome to SLIIT School</div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"description\"style=\"font-size: 30px;color: aliceblue\">\r\n");
      out.write("                    Education is the key to Unlocking the world ,A Passport to freedom.\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"button\">\r\n");
      out.write("                    <button>LOGIN</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"./images/img7.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"title\"style=\"font-size: 80px;color: aliceblue;\">Clubs</div>\r\n");
      out.write("                <div class=\"type\"style=\"font-size: 80px;color: aliceblue;\">& Societies</div>\r\n");
      out.write("                <div class=\"description\"style=\"font-size: 16px; color: aliceblue\">\r\n");
      out.write("                    School clubs and societies provide students with valuable opportunities to explore their interests, develop new skills, and foster a sense of community. These extracurricular groups, ranging from academic societies to sports teams and cultural clubs, help students build leadership, teamwork, and social skills outside the classroom. Participation in such activities not only enhances students' personal growth but also enriches their overall educational experience, preparing them for future challenges in both academic and professional settings.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"button\">\r\n");
      out.write("                    <button>Explore</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"./images/img5.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"title\"style=\"font-size: 80px;color: aliceblue;\">Sports</div>\r\n");
      out.write("                <div class=\"type\"style=\"font-size: 80px;color: aliceblue;\">with Leadership</div>\r\n");
      out.write("                <div class=\"description\"style=\"font-size: 16px; color: aliceblue\">\r\n");
      out.write("                    Sports play a vital role in developing leadership skills by promoting teamwork, discipline, and strategic thinking. Athletes often find themselves in situations that require quick decision-making, effective communication, and the ability to motivate others—all key qualities of strong leaders. Through sports, individuals learn to take responsibility, lead by example, and handle both success and failure with grace. These experiences help shape confident and resilient leaders, equipped to tackle challenges both on and off the field.\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"button\">\r\n");
      out.write("                    <button>Explore</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"./images/free-photo-of-audience-standing-with-arms-raised.jpeg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"title\" style = \"font-size: 80px; color: aliceblue;\">Event</div>\r\n");
      out.write("                <div class=\"type\"style = \"font-size: 80px; color: aliceblue;\">& News</div>\r\n");
      out.write("                <div class=\"description\"style=\"font-size: 16px; color: aliceblue\">\r\n");
      out.write("                    School events and news serve as a dynamic platform for celebrating student achievements, fostering community spirit, and keeping everyone informed about important updates. Whether it's academic milestones, cultural festivals, or sports competitions, these events bring the school community together and highlight the diverse talents within it. Regular updates through newsletters or announcements keep students, parents, and staff engaged and aware of upcoming activities, fostering a sense of unity and pride in the school's accomplishments.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"button\">\r\n");
      out.write("                    <button>Explore</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"./images/pexels-photo-2132891.jpeg\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"./images/img7.jpg\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"./images/img5.jpg\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"./images/free-photo-of-audience-standing-with-arms-raised.jpeg\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nextPrevArrows\">\r\n");
      out.write("        <button class=\"prev\"> < </button>\r\n");
      out.write("        <button class=\"next\"> > </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"Home.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer\" >\r\n");
      out.write("        <div style = \"height:250px; width: 460px; float:left; position: absolute; left: 0%; margin-left: inherit;\">\r\n");
      out.write("            <table class = \"table\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><a href = \"https://www.instagram.com/sliitims_official_/\" target=\"_blank\"><img src = \"images/3.png\" title=\"visit our instagram page\"></a></td>\r\n");
      out.write("                    <td><a href = \"https://www.facebook.com/share/gMEFjxw3TwxU4eLd/?mibextid=LQQJ4d\" target=\"_blank\"><img src = \"images/1.png\" title=\"visit our facebook page\"></a></td>\r\n");
      out.write("                    <td><a href = \"https://twitter.com/officialFoodify\" target=\"_blank\"><img src = \"images/2.png\" title=\"visit our twitter page\"></a></td>\r\n");
      out.write("                    <td><img src = \"images/4.png\" title=\"Contact us through Whatsapp : +94(76) 441 4442\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style = \"height:250px; width: 600px; float:left; align-content: center; position: absolute; left:30%;\">\r\n");
      out.write("            <a  href = \"home.html\"><img src = \"images/SLIIT IMS.png\" style = \"width: 220px ; height:180px; margin-left: 29%; border-radius: 10% ; \" ></a>\r\n");
      out.write("            <p style = \"font-weight: 500; margin-left: 29%; color: rgb(47, 54, 66);\">©2024 SliiIMS Inc. All Rights Reserved</p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style = \"height:250px; width: 460px; float:left;align-content: center; position: absolute; left:70%; color: black;font-size: medium;\">\r\n");
      out.write("\r\n");
      out.write("            <ul type = \"none\">\r\n");
      out.write("                <li>✆ +94(76) 441 4442</li>\r\n");
      out.write("                <li>✆ +94(76) 369 7342</li>\r\n");
      out.write("                <li>☏ +94(11) 551 7723</li>\r\n");
      out.write("                <li>✉ info@sliitims.com</li>\r\n");
      out.write("                <li>🔗<a href = \"Home.jsp\" style = \"text-decoration: none; color: rgb(41, 40, 40);\"> www.SliiIMS.com</a></li>\r\n");
      out.write("                <br>\r\n");
      out.write("                <li><a href = \"#\" style = \"text-decoration:underline; color: rgb(62, 62, 63);\">Give Us Your Feedback!</a></li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
